#!/bin/bash
sudo yum install httpd -y
sudo git clone https://github.com/LiangChen0323/DiceGame_Project.git
sudo cp DiceGame_Project/DiceGame/* /var/www/html/
sudo systemctl start httpd
sudo systemctl enable httpd